### ISSUE TITLE
Client::Handler() API: only `.body()`, or `.body()` and `.end()`?

### ISSUE THREAD

**Issue by rjhuijsman** [3rdparty/eventuals-grpc#4]
There has been some discussion about whether...

(Current state, pseudocode)
```cpp
Client::Handler()
  .body([](auto&& response) { 
    // Will be called for every response AND one more time when the stream terminates.
    // Have to check whether `response` is valid here. Invalid response = terminated stream.
  });
```
... is confusing. The discussed alternative is something like...

(Alternative 1, pseudocode)
```cpp
Client::Handler()
  .body([](auto&& response) {
    // Called for every response (only); `response` is always valid.
  })
  .end([]() {
    // Handle the end of the stream, if needed.
  });
```

@benh can share some insight as to why we picked the current state. After that we can discuss whether we now prefer an alternative.

**Comment by benh** [comment]
Thanks @rjhuijsman for this.

The semantics of stream in `stout-eventuals` **does** split up the EOF signal into a separate `ended()` callback (see below ^ for why this was called `ended()` but not `end()`), but the semantics of `ended()` are that you **should not** do anything else with the stream at that point, and abstractions like `Loop()` make sure to not pass you a reference to the stream so you don't make that error.

With gRPC however the "stream" from the server (or client) call might be ended, but that doesn't mean that you can't still use the call to send more requests (or responses). It all depends on the underlying semantics/expectations of the gRPC method. IMHO the real issue is gRPC is based on a "channel" abstraction not a "stream", and `stout-eventuals` doesn't have something like that built-in (yet).

So the semantics were going to be a bit different no matter what: either we'd have an `ended()` where you still might use the reference to the call or we'd have a different `body()`. I ended up deciding to change the semantics of `body()` because:

1. We already had some _special_ semantics  in `body()` regarding the need to relinquish the `borrowed_ptr` in order for us to read the next request/response from the channel. It seemed nicer to lump all the things that needed to be "taught/learned" in one place.
2. Programmers familiar with gRPC APIs already follow a pattern where you they specifically have to check for EOF (or failure) when reading requests/responses:

```c++
auto state = ...;
while (true) {
  if (reader->Read(&response)) {
    // ... update 'state' based on response (and possibly generate a new request).
    call.Write(request);
  } else { // .. handle failure or EOF.
    // ... use 'state' to possibly send a final request and finish.
    call.WriteLast(request);
    call.Finish(status);
}
```

Extrapolating this gives us a `body()` that closely resembles this pattern:

```c++
Client::Handler()
  .body([state = ...](auto& call, auto&& response) {
    if (response) {
      // .. update 'state' based on 'response' and (possibly generate a new request).
      call.Write(request);
    } else { // .. handle failure or EOF.
      // ... use 'state' to possibly send a final request and finish.
      call.Write(request);    
      call.Finish(status);     
    }
  });
``` 

The `ended()` version isn't _that_ far off from the while loop version, but because they are in different scopes you do have more work to do, in particular you need to use `context()` rather than lambda captures:

```c++
Client::Handler()
  .context(State{})
  .body([](auto& state, auto& call, auto&& response) {
    // .. update 'state' based on 'response' and (possibly generate a new request).
    call.Write(request);
  })
  .ended([](auto& state, auto& call) { // .. handle failure or EOF.
    // ... use 'state' to possibly send a final request and finish.
    call.Write(request);    
    call.Finish(status);
  });
``` 

Ok, hopefully that's some helpful history, let's discuss!

 

^ `stout-eventuals` used `ended()` not `end()` because in the original design there were "helper" functions to invoke each of the callbacks such as `start()` and `next()`, and `body()` and some compilers didn't like `end()` because it's apparently a builtin somewhere? That being said, the current design doesn't have these helpers anymore in lieu of just calling the function on the continuation directly, i.e., `k.Ended()` so we could now go and fix up the tense to be consistent!

**Comment by rjhuijsman** [comment]
Thanks Ben!

Just to make sure that we have all the design alternatives on the table, is there also a possibility that we'd handle failure separately from normal termination? For example:

```c++
Client::Handler()
  .context(State{})
  .body([](auto& state, auto& call, auto&& response) {
    // .. update 'state' based on 'response' and (possibly generate a new request).
    call.Write(request);
  })
  .ended([](auto& state, auto& call) { // Handle EOF.
    // ... use 'state' to possibly send a final request and finish.
    call.Write(request);    
    call.Finish(status);
  })
  .failed([](auto& state, auto& call) { // Handle failure.
    // ...
  });
```

As for tenses, I quite like the past tense - it makes it clearer to me I'm not giving an order but handling a state. In fact, I might lean into that: instead of...

    .body([](..., auto&& response) { ... });

... (which I find a slightly confusing name), I'd consider ...

    .responded([](..., auto&& response) { ... });

**Comment by benh** [comment]
Closing this issue after recent refactorings.
